# Generated by Django 4.2.1 on 2023-05-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
