# Generated by Django 4.2.1 on 2023-05-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userfestival'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('stage', models.CharField(max_length=100)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.festival')),
            ],
        ),
    ]
