# Generated by Django 4.2.1 on 2023-06-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lineup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineUp',
        ),
    ]
