# Generated by Django 4.2.1 on 2023-06-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_lineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivallineup',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='festivallineup',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
